version: "3"
services:
  redis:
    image: redis

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER:sentry
      - POSTGRES_PASSWORD:sentry

  sentry_upgrader:
    image: sentry:8.14
    depends_on:
      - redis
      - postgres
    env_file:
      sentry.env
    command: "sentry upgrade"

  web:
    image: sentry:8.14
    depends_on:
      - redis
      - postgres
    env_file:
      sentry.env
    ports:
      - 10020:9000

  worker:
    image: sentry:8.14
    depends_on:
      - redis
      - postgres
    env_file:
      sentry.env
    command: "sentry run worker"

  beat:
    image: sentry:8.14
    depends_on:
      - redis
      - postgres
    env_file:
      sentry.env
    command: "sentry run cron"
